# Generated by Django 4.1.7 on 2023-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodcuct_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
                ('discription', models.CharField(max_length=300)),
            ],
        ),
    ]
