# Generated by Django 4.1.7 on 2023-03-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveproject', '0003_condact_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condact_tb',
            name='email',
        ),
    ]
