# Generated by Django 4.1.7 on 2023-03-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveproject', '0005_image_enter_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_enter_tb',
        ),
    ]
