# Generated by Django 4.1.7 on 2023-03-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveproject', '0006_delete_image_enter_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_enter_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
