# Generated by Django 4.1.7 on 2023-03-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveproject', '0007_image_enter_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='condact_tb',
        ),
    ]
