# Generated by Django 4.1.7 on 2023-03-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveproject', '0008_delete_condact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='condact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
            ],
        ),
    ]
